### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by sarah48** [Insoumis/patrons#10]
« Qu’est-ce que le « patronat » français ? Est-on sûr qu’existe bien une catégorie sociale qui commence avec des auto-entrepreneurs à 1 000 euros par mois et comporte des salaires comme celui de Carlos Ghosn ? » [se demandait Jean-Luc Mélenchon](http://melenchon.fr/2015/10/17/le-medef-un-groupuscule-nullement-representatif/). 

En effet, ce terme « patronat » rassemble des patrons et des entreprises qui n'ont pas grand chose en commun. [En 2014](http://www.lemonde.fr/economie/article/2016/11/08/tout-ce-que-vous-avez-toujours-voulu-savoir-sur-les-entreprises-francaises-en-10-chiffres_5027592_3234.html), sur 4,4 millions d'entreprises en France, seules 274 employaient plus de 5000 salariés. [En 2012](http://www.clesdusocial.com/les-salaries-dans-les-entreprises-en-2012-selon-leur-taille), moins de 1% des entreprises employaient plus de 50 salariés. [En 2011](http://lexpansion.lexpress.fr/entreprises/les-petits-patrons-francais-gagnent-65-fois-moins-que-les-patrons-du-cac-40_1436674.html), le salaire annuel moyen brut d'un dirigeant d'une PME de moins de 20 salariés était d'environ 50 000 euros. Un patron d'une PME de moins de 20 salariés dans le secteur financier touchait environ 3 fois plus qu'un autre travaillant dans le BTP, qui gagnait en moyenne à peine plus de 2 Smic. Pendant qu'un dirigeant d'une entreprise du Cac 40 gagnait en moyenne 4,2 millions. Le patron de Sanofi, Olivier Brandicourt touchait même [presque 17 millions en 2015](http://www.latribune.fr/opinions/blogs/le-blog-du-contrarian/la-verite-sur-les-remunerations-des-patrons-du-cac-40-en-2015-167-6-millions-euros-565651.html), alors qu'[en 2013](https://www.insee.fr/fr/statistiques/1906507?sommaire=1906539), plus de 600 000 patrons d'entreprises sans salariés gagnaient moins d’un Smic.

Et les inégalités entre entreprises sont aussi énormes. [En 2013](https://www.insee.fr/fr/statistiques/1906507?sommaire=1906539), 1 % des entreprises rassemblaient 65 % de la valeur ajoutée, 55 % de l’emploi et 68 % de l’investissement, et seulement 3 000 entreprises concentraient  83 % des exportations. Pour celui qu'on présente souvent abusivement comme [« le patron des patrons »](http://www.leparisien.fr/economie/medef-pierre-gattaz-un-patron-des-patron-peu-connu-et-impopulaire-20-04-2014-3781303.php), [« il faut dire : "les dividendes, c’est merveilleux, c’est magnifique" »](http://www.cadre-dirigeant-magazine.com/actu/pierre-gattaz-patron-patrons-provocateur/). Mais aujourd'hui, plus que jamais, ce sont les plus grosses entreprises qui profitent de cette « financiarisation de l'économie », en distribuant des dividendes records aux actionnaires. [En 2013](http://alternatives-economiques.fr/blogs/chavagneux/2014/03/10/les-distributions-de-dividendes-plombent-l%E2%80%99investissement-des-entreprises/), les entreprises du CAC 40 ont distribué plus de 80 % de leurs profits net sous forme de dividendes, soit 39 milliards, tandis qu'[en 2011](https://www.slideshare.net/lesechos2/etudes-actionnariat-et-dividendes-preuves-lappui), les PME ne distribuaient que 0,3% du total des dividendes versées. 

Dans les faits, ce « monde de l'entreprise » est loin d'être la [«  force unie »](http://www.medef.com/nc/medef-corporate/salle-de-presse/discours/discours/back/102/article/discours-dinvestiture-de-pierre-gattaz-president-du-medef-2.html) que loue P. Gattaz, mais ressemble plus souvent à une lutte « à la vie à la mort » entre petits et gros. Les problèmes interentreprises sont [la principale source de stress pour les petits patrons](http://www.observatoire-amarok.net/sites/default/files/lechat_torres_ripme_2016_vol_29_ndeg3-4_pp_135-159_0.pdf). [2 entreprises sur 3 paient leurs fournisseurs en retard en France](http://www.latribune.fr/economie/france/entreprises-25-des-faillites-sont-liees-a-des-retards-de-paiement-483579.html), et les retards de paiement sont la principale cause de faillite, avec[ « 25% des faillites et 13 milliards d'euros qui manquent dans les caisses des PME »](http://www.lefigaro.fr/conjoncture/2014/01/09/20002-20140109ARTFIG00280-les-delais-de-paiement-principale-cause-des-defaillances-des-entreprises-depuis-la-crise.php). Pour le médiateur interentreprises mis en place par le gouvernement, certaines grosses entreprises  [« se font sciemment du cash sur le dos du fournisseur »](http://www.lefigaro.fr/conjoncture/2014/01/09/20002-20140109ARTFIG00280-les-delais-de-paiement-principale-cause-des-defaillances-des-entreprises-depuis-la-crise.php). « La sous-traitance avec des majors, c’est la mort » déclarait le patron d'une entreprise de BTP [au journal Fakir](http://www.fakirpresse.info/+-80-en-kiosque-308-+). « De toute façon, j’attends que sa boîte crève et après je le rachète » [disait clairement](http://www.fakirpresse.info/+-80-en-kiosque-308-+) le patron d'une grosse boite à propos d'une TPE en conflit avec elle.

Les inégalités et les injustices qui traversent la société sont donc loin d'épargner le monde de l'entreprise et des entrepreneurs. Face à ces problèmes, le programme [« l'avenir en commun »](https://laec.fr/sommaire) de la France Insoumise propose de nombreuses mesures, que nous allons détailler ici. Il faut d'abord rétablir l'équilibre entre TPE-PME et grands groupes, en soutenant les TPE-PME dans leurs conflits avec les grands groupes, en instaurant plus de démocratie pour la désignation des représentants patronaux, et en s'attaquant directement à la finance, pour relancer l'économie réelle. Soutenir les patrons de TPE-PME au quotidien, en les aidant à créer leur entreprise, à payer les salaires et à investir. Les protéger contre le dumping fiscal et social en France, en Europe et à l'international. Parce que l'écologie et la solidarité concernent aussi les entreprises, il faut aussi les aider à faire la transition écologique, et soutenir l'économie sociale et solidaire. Et surtout il faut relancer l'activité et remplir les carnets de commande, grâce à un grand plan d'investissement.

**Comment by DuaelFr** [comment]
**Correction / Féminisation :**

« Qu’est-ce que le "patronat" français ? Est-on sûr qu’existe bien une catégorie sociale qui commence avec des auto-entrepreneurs à 1 000 euros par mois et comporte des salaires comme celui de Carlos Ghosn ? » [se demandait Jean-Luc Mélenchon](http://melenchon.fr/2015/10/17/le-medef-un-groupuscule-nullement-representatif/). 

En effet, ce terme « patronat » rassemble des patron⋅ne⋅s et des entreprises qui n'ont pas grand chose en commun. [En 2014](http://www.lemonde.fr/economie/article/2016/11/08/tout-ce-que-vous-avez-toujours-voulu-savoir-sur-les-entreprises-francaises-en-10-chiffres_5027592_3234.html), sur 4,4 millions d'entreprises en France, seules 274 employaient plus de 5000 salarié⋅e⋅s. [En 2012](http://www.clesdusocial.com/les-salaries-dans-les-entreprises-en-2012-selon-leur-taille), moins de 1% des entreprises employaient plus de 50 salarié⋅e⋅s. [En 2011](http://lexpansion.lexpress.fr/entreprises/les-petits-patrons-francais-gagnent-65-fois-moins-que-les-patrons-du-cac-40_1436674.html), le salaire annuel moyen brut d'un⋅e dirigeant⋅e d'une PME de moins de 20 salarié⋅e⋅s était d'environ 50 000 euros. Un⋅e patron⋅ne d'une PME de moins de 20 salarié⋅e⋅s dans le secteur financier touchait environ 3 fois plus qu'un⋅e autre travaillant dans le BTP, qui gagnait en moyenne à peine plus de 2 Smic. Pendant qu'un⋅e dirigeant⋅e d'une entreprise du CAC 40 gagnait en moyenne 4,2 millions. Le patron de Sanofi, Olivier Brandicourt, touchait même [presque 17 millions en 2015](http://www.latribune.fr/opinions/blogs/le-blog-du-contrarian/la-verite-sur-les-remunerations-des-patrons-du-cac-40-en-2015-167-6-millions-euros-565651.html), alors qu'[en 2013](https://www.insee.fr/fr/statistiques/1906507?sommaire=1906539), plus de 600 000 patron⋅e⋅s d'entreprises sans salarié⋅e⋅s gagnaient moins d’un Smic.

Et les inégalités entre entreprises sont aussi énormes. [En 2013](https://www.insee.fr/fr/statistiques/1906507?sommaire=1906539), 1 % des entreprises rassemblaient 65 % de la valeur ajoutée, 55 % de l’emploi et 68 % de l’investissement, et seulement 3 000 entreprises concentraient  83 % des exportations. Pour celui qu'on présente souvent abusivement comme [« le patron des patrons »](http://www.leparisien.fr/economie/medef-pierre-gattaz-un-patron-des-patron-peu-connu-et-impopulaire-20-04-2014-3781303.php), [« il faut dire : "les dividendes, c’est merveilleux, c’est magnifique" »](http://www.cadre-dirigeant-magazine.com/actu/pierre-gattaz-patron-patrons-provocateur/). Mais aujourd'hui, plus que jamais, ce sont les plus grosses entreprises qui profitent de cette « financiarisation de l'économie » en distribuant des dividendes records aux actionnaires. [En 2013](http://alternatives-economiques.fr/blogs/chavagneux/2014/03/10/les-distributions-de-dividendes-plombent-l%E2%80%99investissement-des-entreprises/), les entreprises du CAC 40 ont distribué plus de 80 % de leurs profits net sous forme de dividendes, soit 39 milliards, tandis qu'[en 2011](https://www.slideshare.net/lesechos2/etudes-actionnariat-et-dividendes-preuves-lappui), les PME ne distribuaient que 0,3% du total des dividendes versés.

Dans les faits, ce « monde de l'entreprise » est loin d'être la [« force unie »](http://www.medef.com/nc/medef-corporate/salle-de-presse/discours/discours/back/102/article/discours-dinvestiture-de-pierre-gattaz-president-du-medef-2.html) que loue P. Gattaz, mais ressemble plus souvent à une lutte « à la vie à la mort » entre petits et gros. Les problèmes inter-entreprises sont [la principale source de stress pour les petit⋅e⋅s patron⋅ne⋅s](http://www.observatoire-amarok.net/sites/default/files/lechat_torres_ripme_2016_vol_29_ndeg3-4_pp_135-159_0.pdf). [2 entreprises sur 3 paient leurs fournisseurs en retard en France](http://www.latribune.fr/economie/france/entreprises-25-des-faillites-sont-liees-a-des-retards-de-paiement-483579.html), et les retards de paiement sont la principale cause de faillite, avec [« 25% des faillites et 13 milliards d'euros qui manquent dans les caisses des PME »](http://www.lefigaro.fr/conjoncture/2014/01/09/20002-20140109ARTFIG00280-les-delais-de-paiement-principale-cause-des-defaillances-des-entreprises-depuis-la-crise.php). Pour le médiateur des entreprises mis en place par le gouvernement, certaines grosses entreprises  [« se font sciemment du cash sur le dos du fournisseur »](http://www.lefigaro.fr/conjoncture/2014/01/09/20002-20140109ARTFIG00280-les-delais-de-paiement-principale-cause-des-defaillances-des-entreprises-depuis-la-crise.php). « La sous-traitance avec des majors, c’est la mort » déclarait le patron d'une entreprise de BTP [au journal Fakir](http://www.fakirpresse.info/+-80-en-kiosque-308-+). « De toute façon, j’attends que sa boîte crève et après je le rachète » [disait clairement](http://www.fakirpresse.info/+-80-en-kiosque-308-+) le patron d'une grosse boite à propos d'une TPE en conflit avec elle.

Les inégalités et les injustices qui traversent la société sont donc loin d'épargner le monde de l'entreprise et des entrepreneur⋅e⋅s. Face à ces problèmes, le programme [« l'avenir en commun »](https://laec.fr/sommaire) de la France Insoumise propose de nombreuses mesures, que nous allons détailler ici. Il faut d'abord rétablir l'équilibre entre TPE-PME et grands groupes, en soutenant les TPE-PME dans leurs conflits avec les grands groupes, en instaurant plus de démocratie pour la désignation des représentant⋅e⋅s patronaux⋅ales, et en s'attaquant directement à la finance, pour relancer l'économie réelle. Soutenir les patron⋅ne⋅s de TPE-PME au quotidien, en les aidant à créer leur entreprise, à payer les salaires et à investir. Les protéger contre le dumping fiscal et social en France, en Europe et à l'international. Parce que l'écologie et la solidarité concernent aussi les entreprises, il faut aussi les aider à faire la transition écologique, et soutenir l'économie sociale et solidaire. Et surtout il faut relancer l'activité et remplir les carnets de commande, grâce à un grand plan d'investissement.
