### ISSUE TITLE
Le programme de la France Insoumise vise un développement éco-responsable et socialement juste. C'est une idée séduisante, mais comment je vais faire avec ma petite structure pour assumer les coûts d'une telle transition ?

### ISSUE THREAD

**Issue by mahoudeau** [Insoumis/patrons#3]
Un développement respectueux de l'environnement et socialement juste est un pré-requis indispensable à la construction d'un avenir en commun.

Pour aider les entreprises qui veulent investir dans la réduction de leur consommation énergétique, de leurs émissions de déchets et de CO2, et qui épousent une dynamique de création d'emplois par l'investissement, une facilité de crédit sera accordée.

Cette facilité de crédit sera possible par la création d'un pôle public bancaire. La création de ce pôle passera par la socialisation des banques généralistes.

**Comment by sarah48** [comment]
Nouvelle proposition:

**Soutenir la transition écologique des entreprises**

Un développement respectueux de l'environnement et socialement juste est un pré-requis indispensable à la construction d'un avenir en commun.

**Facilités de crédits**

Pour aider les entreprises qui veulent investir dans la réduction de leur consommation énergétique, de leurs émissions de déchets et de CO2, et qui épousent une dynamique de création d'emplois par l'investissement, [une facilité de crédit sera accordée.](https://laec.fr/s21m1)

Cette facilité de crédit sera possible par la création d'un [pôle public bancaire](https://avenirencommun.fr/le-livret-banques/). Ce pôle fournira un service public bancaire. Par ailleurs, une licence bancaire globale sera attribuée à la Banque Publique d’Investissement (BPI). Les entrepreneurs pourront donc [solliciter des prêts auprès de cet organisme, pour investir dans la transition écologique](https://avenirencommun.fr/le-livret-banques/).


**Responsabilité juridique, écologique et sociale des donneurs d'ordres**

Aussi, les [entreprises sous-traitantes seront libérées de certaines responsabilité juridiques dans le cadre leurs contrats avec leurs donneurs d'ordres](https://laec.fr/s21m5). Ceux-ci verront donc leurs responsabilité juridique, sociale et écologique étendues.

**Relocalisation de l'économie**

La relocalisation de l'économie dans le cadre du [protectionnisme solidaire](https://avenirencommun.fr/livret-produire-france/) permettra aussi d'améliorer la responsabilité écologique et sociale du pays, tout en profitant aux PME. Cette politique permettra de refuser d'importer des produits fabriqués dans des conditions sociales indignes et écologiquement irresponsables, et elle protègera donc nos entreprises d'une concurrence déloyale et destructrice (lien vers texte sur le plan de relance). Ce principe, ainsi que celui de la [lutte contre la fraude et l'évasion fiscale](https://laec.fr/section/37/terrasser-l-evasion-et-la-fraude-fiscales), permettront aussi de développer certains secteurs, comme celui des services, en taxant les services offshore.
