### ISSUE TITLE
Contre le dumping social en France

### ISSUE THREAD

**Issue by mahoudeau** [Insoumis/patrons#4]
**Contre le dumping social en France :**

Une des causes les plus importantes de concurrence déloyale entre les entreprises est le dumping social. Ce phénomène pousse les entreprises à faire baisser les salaires et les droits de leurs salariés pour être plus « compétitifs » face à leurs concurrents.

**La loi travail : Vers un dumping social généralisé**

La loi travail adoptée récemment, et qui devrait être poussée encore plus loin avec Emmanuel Macron, devrait exacerber ce dumping. En accordant la primauté aux accords d'entreprises sur les accords de branches (ce qu'on appelle la « hiérarchie des normes », ou le « principe de faveur »), et aux accords de branches (et d'entreprises) sur la loi, cela constitue une remise en cause de pans entiers de la loi. Cette loi permet par exemple à un employeur de négocier un accord d’entreprise imposant l’augmentation du temps de travail sans contrepartie salariale (jusqu'à 46h par semaine), ou la réduction du salaire pour un temps de travail équivalent. Elle facilite aussi les licenciements boursiers ou économiques, qui se sont multipliés depuis plus de 15 ans.

Cette loi aura pour effet de [renforcer la concurrence entre les entreprises, en particulier dans certaines branches très concurrentielles comme le commerce ou le BTP](https://www.bastamag.net/Entre-l-Assemblee-et-le-Senat-un-projet-qui-deregule-largement-le-temps-de)… Cette concurrence sera encore plus présente chez les sous-traitants. Les donneurs d’ordre peuvent maintenant jouer de tout leur poids pour exiger de leurs sous-traitants une baisse des coûts. La position de la France Insoumise est très claire sur ce sujet : il s'agit de [supprimer la loi El Khomri](https://laec.fr/s24), et de rétablir la hiérarchie des normes sociales et le principe de faveur.

**Un affaiblissement de l'inspection du travail au profit des plus gros**

L'inspection du travail n'a pas été ménagée ces dernières années. Son affaiblissement s'est d'abord traduit par une baisse importante de ses effectifs. Il y a maintenant [moins de 2000 inspecteurs pour contrôler presque 2 millions d'entreprises](http://www.lemonde.fr/emploi/article/2014/02/03/qui-veut-la-mort-de-l-inspection-du-travail_4359281_1698637.html) depuis la [loi Sapin de 2014, imposée avec le soutien d'Emmanuel Macron](http://www.huffingtonpost.fr/2017/01/19/emmanuel-macron-assume-de-moins-en-moins-son-bilan-de-conseiller/). Cette loi a aussi amenée avec elle l'adoption d'une politique du chiffre qui met les inspecteurs du travail sous pression. Cet affaiblissement s'est encore accru à travers le remplacement de la procédure pénale par des sanctions administratives, et par une remis en cause de l'indépendance de l'inspection du travail.

Cette politique a eu un effet très défavorable pour les PME mais bénéfique pour les grandes entreprises. En effet, il est beaucoup plus complexe de contrôler une grande entreprise qu'une PME, ce qui incite les agents à s'attarder sur des commerces de proximité ou des petites structures plutôt que sur des multinationales, afin de satisfaire aux exigences chiffrées de leur hiérarchie. Pour plus de détails sur ce phénomène, voir sur [le site de l'Inspection Insoumise ici](https://inspectioninsoumise.wordpress.com/2017/04/21/linspection-du-travail-le-cac40-et-les-pme-version-macron-et-version-melenchon/). Les inspecteurs du travail ont non seulement un rôle de contrôle et de sanction, mais sont aussi là pour informer les employeurs et répondre à leurs questions. Or, avec les réductions d'effectifs, en étant submergé par des demandes pressantes d’usagers, l'agent de contrôle ne peut souvent pas répondre à ces demandes.

**Hausse des effectifs, suppression des évaluations chiffrées et création d'un parquet spécialisé en droit du travail**

Il n'est pas normal que les grandes entreprises, où les salariés sont pressés et usés, soient moins contrôlées que les petites entreprises qui se démènent pour boucler chaque mois afin de payer ses salariés. C'est pour cela qu'il est nécessaire de garantir et renforcer les pouvoirs de l'inspection du travail, de [doubler ses effectifs, et de supprimer les évaluations chiffrées des inspecteurs](https://avenirencommun.fr/le-livret-travail/).

Enfin, alors qu'actuellement il n'existe que des juridictions inter-régionales spécialisées, le programme de la France Insoumise prévoit la [création d'un parquet spécialisé en droit du travail](https://avenirencommun.fr/le-livret-travail/). Celui-ci permettrait une certaine centralisation des affaires, et il serait moins susceptible de subir les pressions de notables locaux. Il pourrait donc permettre de rendre visible et de contrôler plus efficacement les infractions des grandes entreprises dont, à l'heure actuelle, personne ne se soucie.

**Comment by sarah48** [comment]
Nouvelle proposition, j'ai pas changé grand chose


L'inspection du travail n'a pas été ménagée ces dernières années. Son affaiblissement s'est traduit par l'adoption d'une politique du chiffre, qui met les inspecteurs du travail sous pression. Cet affaiblissement s'est aussi fait par le remplacement de la procédure pénale par des sanctions administratives.

Cette politique a eu un effet très bénéfique pour les grandes entreprises et défavorable aux PME. En effet, il est beaucoup plus complexe de contrôler une grande entreprise qu'une PME, ce qui incite les agents à s'attarder sur des commerces de proximité ou des petites structures plutôt que sur des multinationales, afin de satisfaire aux exigences chiffrées de leur hiérarchie.

Il n'est pas normal que les grandes entreprises, où les salariés sont pressés et usés, soient moins contrôlées que les petites entreprises qui se démènent pour finir les mois. C'est pour cela qu'il est nécessaire de garantir et renforcer les pouvoirs de l'inspection du travail, [de doubler ses effectifs, et de supprimer les évaluations chiffrées des inspecteurs](https://avenirencommun.fr/le-livret-travail/).

**Comment by Inspecteur-Gadget** [comment]
J'ajoute un lien vers le site de l'IT insoumise qui explique bien le coup des amendes administratives :

L'inspection du travail n'a pas été ménagée ces dernières années. Son affaiblissement s'est traduit par l'adoption d'une politique du chiffre, qui met les inspecteurs du travail sous pression. Cet affaiblissement s'est aussi fait par le remplacement de la procédure pénale par des sanctions administratives.

Cette politique a eu un effet très bénéfique pour les grandes entreprises et défavorable aux PME. En effet, il est beaucoup plus complexe de contrôler une grande entreprise qu'une PME, ce qui incite les agents à s'attarder sur des commerces de proximité ou des petites structures plutôt que sur des multinationales, afin de satisfaire aux exigences chiffrées de leur hiérarchie. Pour plus de détails sur ce phénomène, voir sur le site de l'Inspection Insoumise : [ici.](https://inspectioninsoumise.wordpress.com/2017/04/21/linspection-du-travail-le-cac40-et-les-pme-version-macron-et-version-melenchon/)

Il n'est pas normal que les grandes entreprises, où les salariés sont pressés et usés, soient moins contrôlées que les petites entreprises qui se démènent pour finir les mois. C'est pour cela qu'il est nécessaire de garantir et renforcer les pouvoirs de l'inspection du travail, [de doubler ses effectifs, et de supprimer les évaluations chiffrées des inspecteurs.](https://avenirencommun.fr/le-livret-travail/)

**Comment by sarah48** [comment]
Merci inspecteur-gadget, nouvelle proposition avec des petites corrections, et ajout d'un passage sur les baisses d'effectifs et de la loi sapin, et d'un idée tirée du blog des inspecteurs insoumis:

"L'inspection du travail n'a pas été ménagée ces dernières années. Son affaiblissement s'est d'abord traduit par une baisse importante de ses effectifs: Il y a maintenant [moins de 2000 inspecteurs pour contrôler presque 2 millions d'entreprises](http://www.lemonde.fr/emploi/article/2014/02/03/qui-veut-la-mort-de-l-inspection-du-travail_4359281_1698637.html), après la [loi Sapin de 2014, imposée avec le soutien d'E.Macron](http://www.huffingtonpost.fr/2017/01/19/emmanuel-macron-assume-de-moins-en-moins-son-bilan-de-conseiller/). Il s'est aussi traduit par l'adoption d'une politique du chiffre, qui met les inspecteurs du travail sous pression. Enfin, cet affaiblissement s'est aussi fait à travers le remplacement de la procédure pénale par des sanctions administratives.

Cette politique a eu un effet très bénéfique pour les grandes entreprises, et défavorable pour les PME. En effet, il est beaucoup plus complexe de contrôler une grande entreprise qu'une PME, ce qui incite les agents à s'attarder sur des commerces de proximité ou des petites structures plutôt que sur des multinationales, afin de satisfaire aux exigences chiffrées de leur hiérarchie. Pour plus de détails sur ce phénomène, voir sur [le site de l'Inspection Insoumise ici](https://inspectioninsoumise.wordpress.com/2017/04/21/linspection-du-travail-le-cac40-et-les-pme-version-macron-et-version-melenchon/).

Les inspecteurs du travail ont non seulement un rôle de contrôle et de sanction, mais aussi d'information des employeurs. Or, avec les réductions d'effectifs, en étant submergé par des demandes pressantes d’usagers, l'agent de contrôle ne peut souvent pas répondre à ces demandes.

Il n'est pas normal que les grandes entreprises, où les salariés sont pressés et usés, soient moins contrôlées que les petites entreprises qui se démènent pour finir les mois. C'est pour cela qu'il est nécessaire de garantir et renforcer les pouvoirs de l'inspection du travail, [de doubler ses effectifs, et de supprimer les évaluations chiffrées des inspecteurs.](https://avenirencommun.fr/le-livret-travail/)"


Sinon, sur le blog, il y a ce passage:

"Les nouveaux pouvoirs sauce Macron, El Khomri, Sapin, Hollande, en matière de sanction, prévoient des alternatives aux poursuites (le fameux « plaider coupable à la française » par exemple), mais également des amendes administratives. Lorsqu’une amende est prononcée, d’une part, elle l’est par un directeur du travail, soumis aux instructions du Préfet le reste du temps. Pas vraiment indépendant tout ça. Le jour où il faudra sanctionner une entreprise qui pèse 700 emplois dans le département, on demande à voir. Mais d’autre part, l’employeur qui voudrait contester la sanction devra se tourner vers le juge administratif, qui, lui, ne pourra soulever de sa propre initiative que certains arguments (moyens d’ordre public). Donc à moins de payer très cher un bon avocat spécialisé, chose facile pour l’entreprise du CAC 40 et difficile pour la PME, la sanction est sans recours."

Et dans le point sur l'inspection des finances dans le programme, il y a ce point: " - Création d'un parquet spécialisé en droit du travail, afin d’améliorer les suites pénales en matière de droit du travail." Penses tu que que ça répond au problème évoqué plus haut?

**Comment by Inspecteur-Gadget** [comment]
Sarah48, quand tu dis "le point sur l'inspection des finances", tu veux dire "l'inspection du travail", non ?
Un parquet spécialisé en droit du travail, ce serait un peu l'équivalent du PNF (parquet national financier). Donc il faut bien lire "UN" parquet (à Paris !) et non plein de petits sous-procureurs dans chaque juridiction. Il y a une solution intermédiaire qui existe déjà : les juridictions interrégionales spécialisées. Il faut bien comprendre une chose : quoiqu'étant des magistrats, les membres du parquet sont soumis à une obligation d'obéissance hiérarchique lorsqu'ils décident de poursuivre ou de ne pas poursuivre. Ce n'est qu'à l'audience qu'ils peuvent requérir comme ils veulent. L'adage les concernant dit "La plume est serve, mais la parole est libre".

Prenons une petite juridiction de province. Le parquet voit arriver des violences conjugales, des stups', des meurtres crapuleux, de la tricherie sur le pinard, et des infractions au code du travail. La tendance est à considérer comme peu importantes ces dernières, surtout si le délinquant est un notable. Et le N+1 du proc-adjoint chargé de tout le volet "affaires financières", qui comprend les infractions au droit du travail, joue au golf avec le patron de la grosse entreprise du coin. De toute façon, le seul code du travail récent disponible pour toute la juridiction date de 2015...

Imaginons maintenant que tous les PV des inspecteurs (et des keufs, ils en font aussi parfois sur des infractions de travail illégal, ou sur les accidents du travail) soient envoyés dans une jolie tour en verre à La Défense, dans un "parquet national travail". A sa tête, un.e procureur.e de la République dispose de plusieurs services spécialisés : travail illégal, précarité, harcèlements et discriminations, santé et sécurité au travail... Là la comparaison va se faire entre situations semblables. Et la question de savoir si untel ou untel va être coopté au sein de telle section du rotary club s'éloigne...

Mais il faut bien voir une chose : ce n'est jouable, et souhaitable, que dans la situation critique actuelle, ou grosso-modo certaines infractions ne sont plus du tout poursuivies. Le PNF malgré son nom ne traite pas toutes les affaires financières, mais seulement les plus complexes ou qui demandent une forte spécialisation. Car il faut compter avec les distances ! Donc pour ma part, je pense que l'intérêt d'un tel parquet, c'est de visibiliser les infractions dont, à l'heure actuelle, personne ne se soucie. Exemple : la précarité. Un "PNT" qui n'aurait que les infractions aux CDD et intérim comme compétences exclusives, et qui s'occuperait du reste seulement sur renvoi, serait déjà très bien.

**Comment by sarah48** [comment]
Oui, j'ai fait une erreur c'est bien "inspection du travail" et non "inspection des finances" bien sur.
Du coup j'ai rajouté un paragraphe à la fin la dessus, en espérant ne pas faire d'erreur. N'hésites pas à modifier toi meme si ça ne te convient pas. Le but c'est de résumer assez rapidement, et que ça soit compréhensible pour des gens qui n'y connaissent pas grand chose.

Sinon, je viens de penser à une autre question. En fait, un des grands problèmes des PME, c'est le fait que les grandes entreprises ne les payent pas, elles rallongent les délais de paiement, font pressions sur elles pour obtenir des ristournes, etc. Est ce que l'augmentation des effectifs permettrait de lutter contre ce problème, est ce que ça fait partie des attributions des inspecteurs du travail? Ca permettrait de rajouter ça dans le texte, ça pourrait être un bon argument.

Et aussi, je viens de voir cette mesure dans le livret "justice", je pense que ça va dans le meme sens que la création d'un parquet spécialisé en droit du travail?  : "'Renforcement de la lutte contre la corruption, la délinquance en « col blanc », les infractions sanitaires, environnementales et de droit pénal du travail : nous alourdirons les peines et doterons chaque département d’un pôle spécialisé regroupant ces matières."

Et dernier point, désolée ça fait peut etre beaucoup, je viens de prendre connaissance de l'affaire Téfal: http://www.lemonde.fr/police-justice/article/2016/11/16/affaire-tefal-la-condamnation-de-l-inspectrice-du-travail-confirmee-en-appel_5032203_1653578.html
Penses tu que les mesures de l'aec auraient un effet contre ce genre d'affaire (pression d'une grande entreprise sur les superieurs hierarchique de l'inspecteur, attaque en justice pour "violation du secret professionnel et recel de documents confidentiels")...? Dans cas peut etre que ça un rapport avec la réforme voulue par la FI sur les lanceurs d'alertes.


Le texte actuel:

"L'inspection du travail n'a pas été ménagée ces dernières années. Son affaiblissement s'est d'abord traduit par une baisse importante de ses effectifs: Il y a maintenant [moins de 2000 inspecteurs pour contrôler presque 2 millions d'entreprises](http://www.lemonde.fr/emploi/article/2014/02/03/qui-veut-la-mort-de-l-inspection-du-travail_4359281_1698637.html), après la [loi Sapin de 2014, imposée avec le soutien d'E.Macron](http://www.huffingtonpost.fr/2017/01/19/emmanuel-macron-assume-de-moins-en-moins-son-bilan-de-conseiller/). Il s'est aussi traduit par l'adoption d'une politique du chiffre, qui met les inspecteurs du travail sous pression. Enfin, cet affaiblissement s'est aussi fait à travers le remplacement de la procédure pénale par des sanctions administratives.


Cette politique a eu un effet très bénéfique pour les grandes entreprises, et défavorable pour les PME. En effet, il est beaucoup plus complexe de contrôler une grande entreprise qu'une PME, ce qui incite les agents à s'attarder sur des commerces de proximité ou des petites structures plutôt que sur des multinationales, afin de satisfaire aux exigences chiffrées de leur hiérarchie. Pour plus de détails sur ce phénomène, voir sur [le site de l'Inspection Insoumise ici](https://inspectioninsoumise.wordpress.com/2017/04/21/linspection-du-travail-le-cac40-et-les-pme-version-macron-et-version-melenchon/).

Les inspecteurs du travail ont non seulement un rôle de contrôle et de sanction, mais aussi d'information des employeurs. Or, avec les réductions d'effectifs, en étant submergé par des demandes pressantes d’usagers, l'agent de contrôle ne peut souvent pas répondre à ces demandes.

**Hausse des effectifs, suppression des évaluations chiffrées et création d'un parquet spécialisé en droit du travail**

Il n'est pas normal que les grandes entreprises, où les salariés sont pressés et usés, soient moins contrôlées que les petites entreprises qui se démènent pour finir les mois. C'est pour cela qu'il est nécessaire de garantir et renforcer les pouvoirs de l'inspection du travail, [de doubler ses effectifs, et de supprimer les évaluations chiffrées des inspecteurs.](https://avenirencommun.fr/le-livret-travail/)

Enfin, alors qu'actuellement il n'existe que des juridictions interrégionales spécialisées, le programme de la FI prévoit la [création d'un parquet spécialisé en droit du travail](https://avenirencommun.fr/le-livret-travail/). Celui-ci permettrait une certaine centralisation des affaires, et il serait moins susceptible de subir les pressions de notables locaux. Il pourrait donc permettre de rendre visible et de contrôler plus efficacement les infractions des grandes entreprises dont, à l'heure actuelle, personne ne se soucie."

**Comment by sarah48** [comment]
Nouvelle version, en élargissant au dumping social en France, et du coup en ajoutant une partie sur la loi El Khomri

**Contre le dumping social en France :** 


Une des causes les plus importantes de concurrence déloyale entre les entreprises est le dumping social, qui pousse les entreprises à faire baisser les salaires et les droits de leurs salariés pour être plus « compétitifs » face à leurs concurrents. 

**La loi travail : Vers un dumping social généralisé**

La loi travail adoptée récemment, et qui devrait être poussée encore plus loin avec Emmanuel Macron, devrait exacerber ce dumping, en accordant la primauté aux accords d'entreprises sur les accords de branches (ce qu'on appelle la « hiérarchie des normes », ou le « principe de faveur »), et aux accords de branches (et d'entreprises) sur la loi, ce qui constitue une remise en cause de pans entiers de la loi. Cette loi permet par exemple à un employeur de négocier un accord d’entreprise imposant l’augmentation du temps de travail sans contrepartie salariale (jusqu'à 46h par semaine), ou la réduction du salaire pour un temps de travail équivalent. Elle facilite aussi les licenciements boursiers ou économiques, qui se sont multipliés depuis plus de 15 ans. 

Cette loi aura pour effet de [renforcer la concurrence entre les entreprises, en particulier dans certaines branches très concurrentielles](https://www.bastamag.net/Entre-l-Assemblee-et-le-Senat-un-projet-qui-deregule-largement-le-temps-de) comme le commerce ou  le BTP… Et en particulier chez les sous-traitants. Les donneurs d’ordre peuvent en effet jouer de tout leur poids pour exiger de leurs sous-traitants une baisse des coûts. La position de la France Insoumise est très claire sur ce sujet : il s'agit de[ supprimer la loi El Khomri](https://laec.fr/s24), et de rétablir la hiérarchie des normes sociales et le principe de faveur.

**Un affaiblissement de l'inspection du travail au profit des plus gros**

L'inspection du travail n'a pas été ménagée ces dernières années. Son affaiblissement s'est d'abord traduit par une baisse importante de ses effectifs: Il y a maintenant [moins de 2000 inspecteurs pour contrôler presque 2 millions d'entreprises](http://www.lemonde.fr/emploi/article/2014/02/03/qui-veut-la-mort-de-l-inspection-du-travail_4359281_1698637.html), après la [loi Sapin de 2014, imposée avec le soutien d'E.Macron](http://www.huffingtonpost.fr/2017/01/19/emmanuel-macron-assume-de-moins-en-moins-son-bilan-de-conseiller/). Il s'est aussi traduit par l'adoption d'une politique du chiffre, qui met les inspecteurs du travail sous pression. Cet affaiblissement s'est aussi fait à travers le remplacement de la procédure pénale par des sanctions administratives, et par une remis en cause de l'indépendance de l'inspection du travail.

Cette politique a eu un effet très bénéfique pour les grandes entreprises, et défavorable pour les PME. En effet, il est beaucoup plus complexe de contrôler une grande entreprise qu'une PME, ce qui incite les agents à s'attarder sur des commerces de proximité ou des petites structures plutôt que sur des multinationales, afin de satisfaire aux exigences chiffrées de leur hiérarchie. Pour plus de détails sur ce phénomène, voir sur [le site de l'Inspection Insoumise ici](https://inspectioninsoumise.wordpress.com/2017/04/21/linspection-du-travail-le-cac40-et-les-pme-version-macron-et-version-melenchon/). Les inspecteurs du travail ont non seulement un rôle de contrôle et de sanction, mais aussi d'information des employeurs. Or, avec les réductions d'effectifs, en étant submergé par des demandes pressantes d’usagers, l'agent de contrôle ne peut souvent pas répondre à ces demandes.

**Hausse des effectifs, suppression des évaluations chiffrées et création d'un parquet spécialisé en droit du travail**

Il n'est pas normal que les grandes entreprises, où les salariés sont pressés et usés, soient moins contrôlées que les petites entreprises qui se démènent pour finir les mois. C'est pour cela qu'il est nécessaire de garantir et renforcer les pouvoirs de l'inspection du travail, [de doubler ses effectifs, et de supprimer les évaluations chiffrées des inspecteurs.](https://avenirencommun.fr/le-livret-travail/)

Enfin, alors qu'actuellement il n'existe que des juridictions interrégionales spécialisées, le programme de la FI prévoit la [création d'un parquet spécialisé en droit du travail](https://avenirencommun.fr/le-livret-travail/). Celui-ci permettrait une certaine centralisation des affaires, et il serait moins susceptible de subir les pressions de notables locaux. Il pourrait donc permettre de rendre visible et de contrôler plus efficacement les infractions des grandes entreprises dont, à l'heure actuelle, personne ne se soucie.
